// Copyright (c) Wieslaw Soltes. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ProDataGrid.SourceGenerators;

public sealed partial class ProDataGridGenerator
{
    internal const string GenerateColumnsAttributeName = "ProDataGrid.SourceGeneration.GenerateDataGridColumnsAttribute";
    internal const string GenerateColumnsForNamespaceAttributeName = "ProDataGrid.SourceGeneration.GenerateDataGridColumnsForNamespaceAttribute";
    internal const string GenerateViewModelAttributeName = "ProDataGrid.SourceGeneration.GenerateDataGridViewModelAttribute";
    internal const string GenerateViewModelsForNamespaceAttributeName = "ProDataGrid.SourceGeneration.GenerateDataGridViewModelsForNamespaceAttribute";
    internal const string ColumnAttributeName = "ProDataGrid.SourceGeneration.DataGridColumnAttribute";
    internal const string IgnoreColumnAttributeName = "ProDataGrid.SourceGeneration.DataGridIgnoreColumnAttribute";
    internal const string GenerateViewAttributeName = "ProDataGrid.SourceGeneration.GenerateDataGridViewAttribute";
    internal const string GenerateViewsForNamespaceAttributeName = "ProDataGrid.SourceGeneration.GenerateDataGridViewsForNamespaceAttribute";

    private static void RegisterAttributeSources(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static postInitializationContext =>
            postInitializationContext.AddSource(
                "ProDataGrid.SourceGeneration.Attributes.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));
    }

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        using System;

        namespace ProDataGrid.SourceGeneration
        {
            internal enum DataGridColumnKind
            {
                Auto,
                Text,
                CheckBox,
                Hyperlink,
                Image,
                Numeric,
                ProgressBar,
                Slider,
                DatePicker,
                TimePicker,
                MaskedText,
                AutoComplete,
                ToggleButton,
                ToggleSwitch,
                Hierarchical,
                CustomDrawing,
                ComboBoxSelectedItem,
                ComboBoxSelectedValue,
                ComboBoxText,
                Template,
                Button,
                Formula
            }

            internal enum DataGridColumnDiscovery
            {
                PublicProperties,
                AttributedOnly
            }

            internal enum DataGridViewFramework
            {
                Avalonia,
                ReactiveUI
            }

            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
            internal sealed class GenerateDataGridColumnsAttribute : Attribute
            {
                public GenerateDataGridColumnsAttribute() { }
                public GenerateDataGridColumnsAttribute(Type itemType) { ItemType = itemType; }

                public Type? ItemType { get; }
                public string? ProviderName { get; set; }
                public string? ProviderNamespace { get; set; }
                public DataGridColumnDiscovery Discovery { get; set; } = DataGridColumnDiscovery.PublicProperties;
                public bool IncludeInherited { get; set; } = true;
                public bool Strict { get; set; } = true;
                public bool Streaming { get; set; }
                public Type? ImplementationType { get; set; }
                public string? ConfigureMethod { get; set; }
            }

            [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
            internal sealed class GenerateDataGridColumnsForNamespaceAttribute : Attribute
            {
                public GenerateDataGridColumnsForNamespaceAttribute(string namespaceName) { NamespaceName = namespaceName; }

                public string NamespaceName { get; }
                public bool IncludeNestedNamespaces { get; set; } = true;
                public DataGridColumnDiscovery Discovery { get; set; } = DataGridColumnDiscovery.PublicProperties;
                public bool IncludeInherited { get; set; } = true;
                public bool Strict { get; set; } = true;
                public bool Streaming { get; set; }
            }

            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
            internal sealed class GenerateDataGridViewModelAttribute : Attribute
            {
                public GenerateDataGridViewModelAttribute(Type itemType) { ItemType = itemType; }
                public GenerateDataGridViewModelAttribute(Type viewModelType, Type itemType)
                {
                    ViewModelType = viewModelType;
                    ItemType = itemType;
                }

                public Type? ViewModelType { get; }
                public Type ItemType { get; }
                public string ColumnDefinitionsPropertyName { get; set; } = "ColumnDefinitions";
                public string SchemaPropertyName { get; set; } = "DataGridSchema";
                public string FastPathOptionsPropertyName { get; set; } = "FastPathOptions";
                public string? ProviderName { get; set; }
                public bool Strict { get; set; } = true;
                public bool Streaming { get; set; }
            }

            [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
            internal sealed class GenerateDataGridViewModelsForNamespaceAttribute : Attribute
            {
                public GenerateDataGridViewModelsForNamespaceAttribute(string namespaceName) { NamespaceName = namespaceName; }

                public string NamespaceName { get; }
                public bool IncludeNestedNamespaces { get; set; } = true;
                public string ItemsPropertyName { get; set; } = "Items";
                public string ColumnDefinitionsPropertyName { get; set; } = "ColumnDefinitions";
                public string SchemaPropertyName { get; set; } = "DataGridSchema";
                public string FastPathOptionsPropertyName { get; set; } = "FastPathOptions";
                public bool Strict { get; set; } = true;
                public bool Streaming { get; set; }
            }

            [AttributeUsage(AttributeTargets.Class | AttributeTargets.Assembly, AllowMultiple = true, Inherited = false)]
            internal sealed class GenerateDataGridViewAttribute : Attribute
            {
                public GenerateDataGridViewAttribute(Type itemType) { ItemType = itemType; }
                public GenerateDataGridViewAttribute(Type viewModelType, Type itemType)
                {
                    ViewModelType = viewModelType;
                    ItemType = itemType;
                }

                public Type? ViewModelType { get; }
                public Type ItemType { get; }
                public string? ViewName { get; set; }
                public string? ViewNamespace { get; set; }
                public DataGridViewFramework Framework { get; set; } = DataGridViewFramework.Avalonia;
                public Type? BaseType { get; set; }
                public string? Title { get; set; }
                public string ItemsPropertyName { get; set; } = "Items";
                public string ColumnDefinitionsPropertyName { get; set; } = "ColumnDefinitions";
                public string FastPathOptionsPropertyName { get; set; } = "FastPathOptions";
                public string? SortingModelPropertyName { get; set; }
                public string? FilteringModelPropertyName { get; set; }
                public string? SearchModelPropertyName { get; set; }
                public string? SearchTextPropertyName { get; set; }
            }

            [AttributeUsage(AttributeTargets.Assembly, AllowMultiple = true)]
            internal sealed class GenerateDataGridViewsForNamespaceAttribute : Attribute
            {
                public GenerateDataGridViewsForNamespaceAttribute(string namespaceName) { NamespaceName = namespaceName; }

                public string NamespaceName { get; }
                public bool IncludeNestedNamespaces { get; set; } = true;
                public DataGridViewFramework Framework { get; set; } = DataGridViewFramework.Avalonia;
                public Type? BaseType { get; set; }
                public string ItemsPropertyName { get; set; } = "Items";
                public string ColumnDefinitionsPropertyName { get; set; } = "ColumnDefinitions";
                public string FastPathOptionsPropertyName { get; set; } = "FastPathOptions";
                public string? SortingModelPropertyName { get; set; }
                public string? FilteringModelPropertyName { get; set; }
                public string? SearchModelPropertyName { get; set; }
                public string? SearchTextPropertyName { get; set; }
            }

            [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
            internal sealed class DataGridColumnAttribute : Attribute
            {
                public DataGridColumnAttribute() { }
                public DataGridColumnAttribute(DataGridColumnKind kind) { Kind = kind; }

                public DataGridColumnKind Kind { get; set; } = DataGridColumnKind.Auto;
                public string? Header { get; set; }
                public int Order { get; set; }
                public string? ColumnKey { get; set; }
                public string? SortMemberPath { get; set; }
                public string? Width { get; set; }
                public double MinWidth { get; set; }
                public double MaxWidth { get; set; }
                public bool CanUserSort { get; set; }
                public bool CanUserHide { get; set; }
                public bool CanUserResize { get; set; }
                public bool CanUserReorder { get; set; }
                public bool IsReadOnly { get; set; }
                public bool IsVisible { get; set; }
                public bool ShowFilterButton { get; set; }
                public string? HeaderTemplateKey { get; set; }
                public string? HeaderThemeKey { get; set; }
                public string? CellThemeKey { get; set; }
                public string? SummaryCellThemeKey { get; set; }
                public string? FilterThemeKey { get; set; }
                public string? FilterFlyoutKey { get; set; }
                public string? WidthSharingGroup { get; set; }
                public string? FormatString { get; set; }
                public string? Watermark { get; set; }
                public string? TemplateKey { get; set; }
                public string? EditingTemplateKey { get; set; }
                public string? Formula { get; set; }
                public string? FormulaName { get; set; }
                public string? Mask { get; set; }
                public string? Content { get; set; }
                public string? ItemsSourceMember { get; set; }
                public string? DisplayMemberPath { get; set; }
                public string? SelectedValuePath { get; set; }
                public double Minimum { get; set; }
                public double Maximum { get; set; }
                public double Increment { get; set; }
                public bool IsThreeState { get; set; }
                public bool IsEditable { get; set; }
                public bool IsSearchable { get; set; }
                public string? SearchMemberPath { get; set; }
                public string? ConfigureMethod { get; set; }
                public string? FactoryMethod { get; set; }
            }

            [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
            internal sealed class DataGridIgnoreColumnAttribute : Attribute
            {
            }
        }
        """;
}
