<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Avalonia.Controls.DataGrid/Avalonia.Controls.DataGrid.csproj" />
    <ProjectReference Include="../../src/ProDataGrid.Charting/ProDataGrid.Charting.csproj" />
    <ProjectReference Include="../../src/ProCharts/ProCharts.csproj" />
    <ProjectReference Include="../../src/ProDataGrid.SourceGenerators/ProDataGrid.SourceGenerators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="true" />
  </ItemGroup>

</Project>
