using System;
using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace Avalonia.Controls;

internal static partial class DataGridDiagnostics
{
    private static Histogram<double>? s_dataGridRefresh;
    private static Histogram<double>? s_rowsRefresh;
    private static Histogram<double>? s_rowsDisplayUpdate;
    private static Histogram<double>? s_rowsPresenterViewportChanged;
    private static Histogram<double>? s_rowsScrollSlotsByHeight;
    private static Histogram<double>? s_rowsScrollEstimateOffset;
    private static Histogram<double>? s_rowsMeasure;
    private static Histogram<double>? s_rowsArrange;
    private static Histogram<double>? s_dataGridMeasure;
    private static Histogram<double>? s_dataGridArrange;
    private static Histogram<double>? s_cellsMeasure;
    private static Histogram<double>? s_cellsArrange;
    private static Histogram<double>? s_rowMeasure;
    private static Histogram<double>? s_rowArrange;
    private static Histogram<double>? s_rowsDisplayElementInsert;
    private static Histogram<double>? s_rowsDisplayElementAttach;
    private static Histogram<double>? s_rowsDisplayElementMeasure;
    private static Histogram<double>? s_rowsDisplayElementHeightRecord;
    private static Histogram<double>? s_rowsDisplayElementLoad;
    private static Histogram<double>? s_rowsScrollViewportDelta;
    private static Histogram<double>? s_rowsScrollExtentDelta;
    private static Histogram<double>? s_rowsLogicalOffsetSynchronizedDelta;
    private static Histogram<double>? s_rowGenerate;
    private static Histogram<double>? s_columnsAutoGenerate;
    private static Histogram<double>? s_selectionChanged;
    private static Histogram<double>? s_collectionRefresh;
    private static Histogram<double>? s_collectionFilter;
    private static Histogram<double>? s_collectionSort;
    private static Histogram<double>? s_collectionGroup;
    private static Histogram<double>? s_collectionGroupTemporary;
    private static Histogram<double>? s_collectionGroupPage;

    private static Counter<long>? s_rowsRealized;
    private static Counter<long>? s_rowsRecycled;
    private static Counter<long>? s_rowsPrepared;
    private static Counter<long>? s_rowsMeasured;
    private static Counter<long>? s_rowsMeasureSkipped;
    private static Counter<long>? s_rowsArranged;
    private static Counter<long>? s_rowsArrangeSkipped;
    private static Counter<long>? s_rowsArrangeMeasureInvalidated;
    private static Counter<long>? s_rowsScrollInfoChanged;
    private static Counter<long>? s_rowsScrollExtentChanged;
    private static Counter<long>? s_rowsScrollViewportChanged;
    private static Counter<long>? s_rowsScrollOffsetCoerced;
    private static Counter<long>? s_rowsScrollInvalidated;
    private static Counter<long>? s_rowsScrollExactSlotHeightLookups;
    private static Counter<long>? s_rowsScrollExactSlotHeightInsertions;
    private static Counter<long>? s_rowsLogicalOffsetSynchronized;
    private static Counter<long>? s_columnsAutoGenerated;
    private static Counter<long>? s_selectionChangedCount;

    public static void InitMetrics()
    {
        var meter = new Meter(MeterName);

        s_dataGridRefresh = meter.CreateHistogram<double>(
            Meters.DataGridRefreshTimeName,
            Meters.MillisecondsUnit,
            Meters.DataGridRefreshTimeDescription);
        s_rowsRefresh = meter.CreateHistogram<double>(
            Meters.RowsRefreshTimeName,
            Meters.MillisecondsUnit,
            Meters.RowsRefreshTimeDescription);
        s_rowsDisplayUpdate = meter.CreateHistogram<double>(
            Meters.RowsDisplayUpdateTimeName,
            Meters.MillisecondsUnit,
            Meters.RowsDisplayUpdateTimeDescription);
        s_rowsPresenterViewportChanged = meter.CreateHistogram<double>(
            Meters.RowsPresenterViewportChangedTimeName,
            Meters.MillisecondsUnit,
            Meters.RowsPresenterViewportChangedTimeDescription);
        s_rowsScrollSlotsByHeight = meter.CreateHistogram<double>(
            Meters.RowsScrollSlotsByHeightTimeName,
            Meters.MillisecondsUnit,
            Meters.RowsScrollSlotsByHeightTimeDescription);
        s_rowsScrollEstimateOffset = meter.CreateHistogram<double>(
            Meters.RowsScrollEstimateOffsetTimeName,
            Meters.MillisecondsUnit,
            Meters.RowsScrollEstimateOffsetTimeDescription);
        s_rowsMeasure = meter.CreateHistogram<double>(
            Meters.RowsMeasureTimeName,
            Meters.MillisecondsUnit,
            Meters.RowsMeasureTimeDescription);
        s_rowsArrange = meter.CreateHistogram<double>(
            Meters.RowsArrangeTimeName,
            Meters.MillisecondsUnit,
            Meters.RowsArrangeTimeDescription);
        s_dataGridMeasure = meter.CreateHistogram<double>(
            Meters.DataGridMeasureTimeName,
            Meters.MillisecondsUnit,
            Meters.DataGridMeasureTimeDescription);
        s_dataGridArrange = meter.CreateHistogram<double>(
            Meters.DataGridArrangeTimeName,
            Meters.MillisecondsUnit,
            Meters.DataGridArrangeTimeDescription);
        s_cellsMeasure = meter.CreateHistogram<double>(
            Meters.CellsMeasureTimeName,
            Meters.MillisecondsUnit,
            Meters.CellsMeasureTimeDescription);
        s_cellsArrange = meter.CreateHistogram<double>(
            Meters.CellsArrangeTimeName,
            Meters.MillisecondsUnit,
            Meters.CellsArrangeTimeDescription);
        s_rowMeasure = meter.CreateHistogram<double>(
            Meters.RowMeasureTimeName,
            Meters.MillisecondsUnit,
            Meters.RowMeasureTimeDescription);
        s_rowArrange = meter.CreateHistogram<double>(
            Meters.RowArrangeTimeName,
            Meters.MillisecondsUnit,
            Meters.RowArrangeTimeDescription);
        s_rowsDisplayElementInsert = meter.CreateHistogram<double>(
            Meters.RowsDisplayElementInsertTimeName,
            Meters.MillisecondsUnit,
            Meters.RowsDisplayElementInsertTimeDescription);
        s_rowsDisplayElementAttach = meter.CreateHistogram<double>(
            Meters.RowsDisplayElementAttachTimeName,
            Meters.MillisecondsUnit,
            Meters.RowsDisplayElementAttachTimeDescription);
        s_rowsDisplayElementMeasure = meter.CreateHistogram<double>(
            Meters.RowsDisplayElementMeasureTimeName,
            Meters.MillisecondsUnit,
            Meters.RowsDisplayElementMeasureTimeDescription);
        s_rowsDisplayElementHeightRecord = meter.CreateHistogram<double>(
            Meters.RowsDisplayElementHeightRecordTimeName,
            Meters.MillisecondsUnit,
            Meters.RowsDisplayElementHeightRecordTimeDescription);
        s_rowsDisplayElementLoad = meter.CreateHistogram<double>(
            Meters.RowsDisplayElementLoadTimeName,
            Meters.MillisecondsUnit,
            Meters.RowsDisplayElementLoadTimeDescription);
        s_rowsScrollViewportDelta = meter.CreateHistogram<double>(
            Meters.RowsScrollViewportDeltaName,
            "px",
            Meters.RowsScrollViewportDeltaDescription);
        s_rowsScrollExtentDelta = meter.CreateHistogram<double>(
            Meters.RowsScrollExtentDeltaName,
            "px",
            Meters.RowsScrollExtentDeltaDescription);
        s_rowsLogicalOffsetSynchronizedDelta = meter.CreateHistogram<double>(
            Meters.RowsLogicalOffsetSynchronizedDeltaName,
            "px",
            Meters.RowsLogicalOffsetSynchronizedDeltaDescription);
        s_rowGenerate = meter.CreateHistogram<double>(
            Meters.RowGenerateTimeName,
            Meters.MillisecondsUnit,
            Meters.RowGenerateTimeDescription);
        s_columnsAutoGenerate = meter.CreateHistogram<double>(
            Meters.ColumnsAutoGenerateTimeName,
            Meters.MillisecondsUnit,
            Meters.ColumnsAutoGenerateTimeDescription);
        s_selectionChanged = meter.CreateHistogram<double>(
            Meters.SelectionChangedTimeName,
            Meters.MillisecondsUnit,
            Meters.SelectionChangedTimeDescription);
        s_collectionRefresh = meter.CreateHistogram<double>(
            Meters.CollectionRefreshTimeName,
            Meters.MillisecondsUnit,
            Meters.CollectionRefreshTimeDescription);
        s_collectionFilter = meter.CreateHistogram<double>(
            Meters.CollectionFilterTimeName,
            Meters.MillisecondsUnit,
            Meters.CollectionFilterTimeDescription);
        s_collectionSort = meter.CreateHistogram<double>(
            Meters.CollectionSortTimeName,
            Meters.MillisecondsUnit,
            Meters.CollectionSortTimeDescription);
        s_collectionGroup = meter.CreateHistogram<double>(
            Meters.CollectionGroupTimeName,
            Meters.MillisecondsUnit,
            Meters.CollectionGroupTimeDescription);
        s_collectionGroupTemporary = meter.CreateHistogram<double>(
            Meters.CollectionGroupTemporaryTimeName,
            Meters.MillisecondsUnit,
            Meters.CollectionGroupTemporaryTimeDescription);
        s_collectionGroupPage = meter.CreateHistogram<double>(
            Meters.CollectionGroupPageTimeName,
            Meters.MillisecondsUnit,
            Meters.CollectionGroupPageTimeDescription);

        s_rowsRealized = meter.CreateCounter<long>(
            Meters.RowsRealizedCountName,
            Meters.RowsUnit,
            Meters.RowsRealizedCountDescription);
        s_rowsRecycled = meter.CreateCounter<long>(
            Meters.RowsRecycledCountName,
            Meters.RowsUnit,
            Meters.RowsRecycledCountDescription);
        s_rowsPrepared = meter.CreateCounter<long>(
            Meters.RowsPreparedCountName,
            Meters.RowsUnit,
            Meters.RowsPreparedCountDescription);
        s_rowsMeasured = meter.CreateCounter<long>(
            Meters.RowsMeasuredCountName,
            Meters.RowsUnit,
            Meters.RowsMeasuredCountDescription);
        s_rowsMeasureSkipped = meter.CreateCounter<long>(
            Meters.RowsMeasureSkippedCountName,
            Meters.RowsUnit,
            Meters.RowsMeasureSkippedCountDescription);
        s_rowsArranged = meter.CreateCounter<long>(
            Meters.RowsArrangedCountName,
            Meters.RowsUnit,
            Meters.RowsArrangedCountDescription);
        s_rowsArrangeSkipped = meter.CreateCounter<long>(
            Meters.RowsArrangeSkippedCountName,
            Meters.RowsUnit,
            Meters.RowsArrangeSkippedCountDescription);
        s_rowsArrangeMeasureInvalidated = meter.CreateCounter<long>(
            Meters.RowsArrangeMeasureInvalidatedCountName,
            Meters.RowsUnit,
            Meters.RowsArrangeMeasureInvalidatedCountDescription);
        s_rowsScrollInfoChanged = meter.CreateCounter<long>(
            Meters.RowsScrollInfoChangedCountName,
            Meters.RowsUnit,
            Meters.RowsScrollInfoChangedCountDescription);
        s_rowsScrollExtentChanged = meter.CreateCounter<long>(
            Meters.RowsScrollExtentChangedCountName,
            Meters.RowsUnit,
            Meters.RowsScrollExtentChangedCountDescription);
        s_rowsScrollViewportChanged = meter.CreateCounter<long>(
            Meters.RowsScrollViewportChangedCountName,
            Meters.RowsUnit,
            Meters.RowsScrollViewportChangedCountDescription);
        s_rowsScrollOffsetCoerced = meter.CreateCounter<long>(
            Meters.RowsScrollOffsetCoercedCountName,
            Meters.RowsUnit,
            Meters.RowsScrollOffsetCoercedCountDescription);
        s_rowsScrollInvalidated = meter.CreateCounter<long>(
            Meters.RowsScrollInvalidatedCountName,
            Meters.RowsUnit,
            Meters.RowsScrollInvalidatedCountDescription);
        s_rowsScrollExactSlotHeightLookups = meter.CreateCounter<long>(
            Meters.RowsScrollExactSlotHeightLookupCountName,
            Meters.RowsUnit,
            Meters.RowsScrollExactSlotHeightLookupCountDescription);
        s_rowsScrollExactSlotHeightInsertions = meter.CreateCounter<long>(
            Meters.RowsScrollExactSlotHeightInsertionCountName,
            Meters.RowsUnit,
            Meters.RowsScrollExactSlotHeightInsertionCountDescription);
        s_rowsLogicalOffsetSynchronized = meter.CreateCounter<long>(
            Meters.RowsLogicalOffsetSynchronizedCountName,
            Meters.RowsUnit,
            Meters.RowsLogicalOffsetSynchronizedCountDescription);
        s_columnsAutoGenerated = meter.CreateCounter<long>(
            Meters.ColumnsAutoGeneratedCountName,
            Meters.ColumnsUnit,
            Meters.ColumnsAutoGeneratedCountDescription);
        s_selectionChangedCount = meter.CreateCounter<long>(
            Meters.SelectionChangedCountName,
            Meters.SelectionUnit,
            Meters.SelectionChangedCountDescription);
    }

    public static HistogramReportDisposable BeginDataGridRefresh() => Begin(s_dataGridRefresh);
    public static HistogramReportDisposable BeginRowsRefresh() => Begin(s_rowsRefresh);
    public static HistogramReportDisposable BeginRowsDisplayUpdate() => Begin(s_rowsDisplayUpdate);
    public static HistogramReportDisposable BeginRowsPresenterViewportChanged() => Begin(s_rowsPresenterViewportChanged);
    public static HistogramReportDisposable BeginRowsScrollSlotsByHeight() => Begin(s_rowsScrollSlotsByHeight);
    public static HistogramReportDisposable BeginRowsScrollEstimateOffset() => Begin(s_rowsScrollEstimateOffset);
    public static HistogramReportDisposable BeginRowsMeasure() => Begin(s_rowsMeasure);
    public static HistogramReportDisposable BeginRowsArrange() => Begin(s_rowsArrange);
    public static HistogramReportDisposable BeginDataGridMeasure() => Begin(s_dataGridMeasure);
    public static HistogramReportDisposable BeginDataGridArrange() => Begin(s_dataGridArrange);
    public static HistogramReportDisposable BeginCellsMeasure() => Begin(s_cellsMeasure);
    public static HistogramReportDisposable BeginCellsArrange() => Begin(s_cellsArrange);
    public static HistogramReportDisposable BeginRowMeasure() => Begin(s_rowMeasure);
    public static HistogramReportDisposable BeginRowArrange() => Begin(s_rowArrange);
    public static HistogramReportDisposable BeginRowsDisplayElementInsert() => Begin(s_rowsDisplayElementInsert);
    public static HistogramReportDisposable BeginRowsDisplayElementAttach() => Begin(s_rowsDisplayElementAttach);
    public static HistogramReportDisposable BeginRowsDisplayElementMeasure() => Begin(s_rowsDisplayElementMeasure);
    public static HistogramReportDisposable BeginRowsDisplayElementHeightRecord() => Begin(s_rowsDisplayElementHeightRecord);
    public static HistogramReportDisposable BeginRowsDisplayElementLoad() => Begin(s_rowsDisplayElementLoad);
    public static HistogramReportDisposable BeginRowGenerate() => Begin(s_rowGenerate);
    public static HistogramReportDisposable BeginColumnsAutoGenerate() => Begin(s_columnsAutoGenerate);
    public static HistogramReportDisposable BeginSelectionChanged() => Begin(s_selectionChanged);
    public static HistogramReportDisposable BeginCollectionRefresh() => Begin(s_collectionRefresh);
    public static HistogramReportDisposable BeginCollectionFilter() => Begin(s_collectionFilter);
    public static HistogramReportDisposable BeginCollectionSort() => Begin(s_collectionSort);
    public static HistogramReportDisposable BeginCollectionGroup() => Begin(s_collectionGroup);
    public static HistogramReportDisposable BeginCollectionGroupTemporary() => Begin(s_collectionGroupTemporary);
    public static HistogramReportDisposable BeginCollectionGroupPage() => Begin(s_collectionGroupPage);

    public static void RecordRowRealized(string source)
    {
        var counter = s_rowsRealized;
        if (counter is null)
        {
            return;
        }

        TagList tags = default;
        tags.Add(Tags.Source, source);
        counter.Add(1, tags);
    }

    public static void RecordRowRecycled() => s_rowsRecycled?.Add(1);

    public static void RecordRowPrepared() => s_rowsPrepared?.Add(1);

    public static void RecordRowsMeasured(int count) => Record(s_rowsMeasured, count);

    public static void RecordRowsMeasureSkipped(int count) => Record(s_rowsMeasureSkipped, count);

    public static void RecordRowsArranged(int count) => Record(s_rowsArranged, count);

    public static void RecordRowsArrangeSkipped(int count) => Record(s_rowsArrangeSkipped, count);

    public static void RecordRowsArrangeMeasureInvalidated() => s_rowsArrangeMeasureInvalidated?.Add(1);

    public static void RecordRowsScrollInfoChanged() => s_rowsScrollInfoChanged?.Add(1);

    public static void RecordRowsScrollExtentChanged(Size oldExtent, Size newExtent)
    {
        s_rowsScrollExtentChanged?.Add(1);
        s_rowsScrollExtentDelta?.Record(Math.Max(
            Math.Abs(oldExtent.Width - newExtent.Width),
            Math.Abs(oldExtent.Height - newExtent.Height)));
    }

    public static void RecordRowsScrollViewportChanged(Size oldViewport, Size newViewport)
    {
        s_rowsScrollViewportChanged?.Add(1);
        s_rowsScrollViewportDelta?.Record(Math.Max(
            Math.Abs(oldViewport.Width - newViewport.Width),
            Math.Abs(oldViewport.Height - newViewport.Height)));
    }

    public static void RecordRowsScrollOffsetCoerced() => s_rowsScrollOffsetCoerced?.Add(1);

    public static void RecordRowsScrollInvalidated() => s_rowsScrollInvalidated?.Add(1);

    public static void RecordRowsScrollExactSlotHeightLookup(bool inserted)
    {
        s_rowsScrollExactSlotHeightLookups?.Add(1);
        if (inserted)
        {
            s_rowsScrollExactSlotHeightInsertions?.Add(1);
        }
    }

    public static void RecordRowsLogicalOffsetSynchronized(double delta)
    {
        s_rowsLogicalOffsetSynchronized?.Add(1);
        s_rowsLogicalOffsetSynchronizedDelta?.Record(Math.Abs(delta));
    }

    public static void RecordColumnsAutoGenerated(int count)
    {
        if (count <= 0)
        {
            return;
        }

        s_columnsAutoGenerated?.Add(count);
    }

    public static void RecordSelectionChanged(DataGridSelectionChangeSource source)
    {
        var counter = s_selectionChangedCount;
        if (counter is null)
        {
            return;
        }

        TagList tags = default;
        tags.Add(Tags.SelectionSource, source.ToString());
        counter.Add(1, tags);
    }

    private static HistogramReportDisposable Begin(Histogram<double>? histogram)
        => histogram is not null ? new HistogramReportDisposable(histogram) : default;

    private static void Record(Counter<long>? counter, int count)
    {
        if (count > 0)
        {
            counter?.Add(count);
        }
    }

    internal readonly ref struct HistogramReportDisposable
    {
        private readonly Histogram<double>? _histogram;
        private readonly long _timestamp;

        public HistogramReportDisposable(Histogram<double> histogram)
        {
            _histogram = histogram;
            _timestamp = Stopwatch.GetTimestamp();
        }

        public void Dispose()
        {
            if (_histogram is null || _timestamp == 0)
            {
                return;
            }

            var elapsedMs = (Stopwatch.GetTimestamp() - _timestamp) * 1000.0 / Stopwatch.Frequency;
            _histogram.Record(elapsedMs);
        }
    }
}
