// Copyright (c) Wiesław Šoltés. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for details.

#nullable disable

using System;
using System.Globalization;
using Avalonia.Collections;
using Avalonia.Controls.Primitives;
using Avalonia.Controls.Utils;
using Avalonia.Controls.DataGridEditing;
using Avalonia.Data;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Styling;

namespace Avalonia.Controls
{
    /// <summary>
    /// Represents a <see cref="DataGrid" /> column that hosts <see cref="NumericUpDown" /> controls 
    /// for editing numeric values (decimal, double, int) with optional formatting and spinner controls.
    /// </summary>
#if !DATAGRID_INTERNAL
public
#else
internal
#endif
    class DataGridNumericColumn : DataGridBoundColumn, IDataGridDrawnCellValueProvider
    {
        private readonly Lazy<ControlTheme> _cellNumericUpDownTheme;
        private readonly Lazy<ControlTheme> _cellTextBlockTheme;
        private readonly Lazy<ControlTheme> _drawingCellTheme;

        /// <summary>
        /// Gets the theme applied to <see cref="NumericUpDown" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellNumericUpDownTheme => GetThemeValue(_cellNumericUpDownTheme);

        /// <summary>
        /// Gets the theme applied to display <see cref="TextBlock" /> instances generated by the column.
        /// May return null when no matching resource is found.
        /// </summary>
        protected ControlTheme CellTextBlockTheme => GetThemeValue(_cellTextBlockTheme);

        /// <summary>
        /// Initializes a new instance of the <see cref="DataGridNumericColumn"/> class.
        /// </summary>
        public DataGridNumericColumn()
        {
            BindingTarget = NumericUpDown.ValueProperty;
            _cellNumericUpDownTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellNumericUpDownTheme"));
            _cellTextBlockTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridCellNumericTextBlockTheme"));
            _drawingCellTheme = new Lazy<ControlTheme>(() => GetColumnControlTheme("DataGridOptimizedDrawingCellTheme"));
        }

        /// <summary>
        /// Defines the <see cref="FormatString"/> property.
        /// </summary>
        public static readonly StyledProperty<string> FormatStringProperty =
            NumericUpDown.FormatStringProperty.AddOwner<DataGridNumericColumn>();

        /// <summary>
        /// Gets or sets the format string used for displaying the numeric value.
        /// Examples: "C2" for currency, "N2" for number, "P0" for percentage.
        /// </summary>
        public string FormatString
        {
            get => GetValue(FormatStringProperty);
            set => SetValue(FormatStringProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="NumberFormat"/> property.
        /// </summary>
        public static readonly StyledProperty<NumberFormatInfo> NumberFormatProperty =
            NumericUpDown.NumberFormatProperty.AddOwner<DataGridNumericColumn>();

        /// <summary>
        /// Gets or sets the <see cref="NumberFormatInfo"/> used for formatting the numeric value.
        /// </summary>
        public NumberFormatInfo NumberFormat
        {
            get => GetValue(NumberFormatProperty);
            set => SetValue(NumberFormatProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Minimum"/> property.
        /// </summary>
        public static readonly StyledProperty<decimal> MinimumProperty =
            NumericUpDown.MinimumProperty.AddOwner<DataGridNumericColumn>();

        /// <summary>
        /// Gets or sets the minimum allowed value.
        /// </summary>
        public decimal Minimum
        {
            get => GetValue(MinimumProperty);
            set => SetValue(MinimumProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Maximum"/> property.
        /// </summary>
        public static readonly StyledProperty<decimal> MaximumProperty =
            NumericUpDown.MaximumProperty.AddOwner<DataGridNumericColumn>();

        /// <summary>
        /// Gets or sets the maximum allowed value.
        /// </summary>
        public decimal Maximum
        {
            get => GetValue(MaximumProperty);
            set => SetValue(MaximumProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Increment"/> property.
        /// </summary>
        public static readonly StyledProperty<decimal> IncrementProperty =
            NumericUpDown.IncrementProperty.AddOwner<DataGridNumericColumn>();

        /// <summary>
        /// Gets or sets the increment value for spinner operations.
        /// </summary>
        public decimal Increment
        {
            get => GetValue(IncrementProperty);
            set => SetValue(IncrementProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="ShowButtonSpinner"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> ShowButtonSpinnerProperty =
            ButtonSpinner.ShowButtonSpinnerProperty.AddOwner<DataGridNumericColumn>();

        /// <summary>
        /// Gets or sets whether to show the up/down spinner buttons.
        /// </summary>
        public bool ShowButtonSpinner
        {
            get => GetValue(ShowButtonSpinnerProperty);
            set => SetValue(ShowButtonSpinnerProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="ButtonSpinnerLocation"/> property.
        /// </summary>
        public static readonly StyledProperty<Location> ButtonSpinnerLocationProperty =
            ButtonSpinner.ButtonSpinnerLocationProperty.AddOwner<DataGridNumericColumn>();

        /// <summary>
        /// Gets or sets the location of the spinner buttons (Left or Right).
        /// </summary>
        public Location ButtonSpinnerLocation
        {
            get => GetValue(ButtonSpinnerLocationProperty);
            set => SetValue(ButtonSpinnerLocationProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="AllowSpin"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> AllowSpinProperty =
            NumericUpDown.AllowSpinProperty.AddOwner<DataGridNumericColumn>();

        /// <summary>
        /// Gets or sets whether spinning is allowed.
        /// </summary>
        public bool AllowSpin
        {
            get => GetValue(AllowSpinProperty);
            set => SetValue(AllowSpinProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="ClipValueToMinMax"/> property.
        /// </summary>
        public static readonly StyledProperty<bool> ClipValueToMinMaxProperty =
            NumericUpDown.ClipValueToMinMaxProperty.AddOwner<DataGridNumericColumn>();

        /// <summary>
        /// Gets or sets whether to clip the value to the min/max range.
        /// </summary>
        public bool ClipValueToMinMax
        {
            get => GetValue(ClipValueToMinMaxProperty);
            set => SetValue(ClipValueToMinMaxProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="Watermark"/> property.
        /// </summary>
        public static readonly StyledProperty<string> WatermarkProperty =
            NumericUpDown.WatermarkProperty.AddOwner<DataGridNumericColumn>();

        /// <summary>
        /// Gets or sets the placeholder text displayed when the value is null.
        /// </summary>
        public string Watermark
        {
            get => GetValue(WatermarkProperty);
            set => SetValue(WatermarkProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="HorizontalContentAlignment"/> property.
        /// </summary>
        public static readonly StyledProperty<HorizontalAlignment> HorizontalContentAlignmentProperty =
            ContentControl.HorizontalContentAlignmentProperty.AddOwner<DataGridNumericColumn>();

        /// <summary>
        /// Gets or sets the horizontal alignment of the content.
        /// </summary>
        public HorizontalAlignment HorizontalContentAlignment
        {
            get => GetValue(HorizontalContentAlignmentProperty);
            set => SetValue(HorizontalContentAlignmentProperty, value);
        }

        /// <summary>
        /// Defines the <see cref="VerticalContentAlignment"/> property.
        /// </summary>
        public static readonly StyledProperty<VerticalAlignment> VerticalContentAlignmentProperty =
            ContentControl.VerticalContentAlignmentProperty.AddOwner<DataGridNumericColumn>();

        /// <summary>
        /// Gets or sets the vertical alignment of the content.
        /// </summary>
        public VerticalAlignment VerticalContentAlignment
        {
            get => GetValue(VerticalContentAlignmentProperty);
            set => SetValue(VerticalContentAlignmentProperty, value);
        }

        static DataGridNumericColumn()
        {
            HorizontalContentAlignmentProperty.OverrideDefaultValue<DataGridNumericColumn>(HorizontalAlignment.Right);
            SummaryCellHorizontalContentAlignmentProperty.OverrideDefaultValue<DataGridNumericColumn>(HorizontalAlignment.Right);
            ShowButtonSpinnerProperty.OverrideDefaultValue<DataGridNumericColumn>(true);
            AllowSpinProperty.OverrideDefaultValue<DataGridNumericColumn>(true);
            ClipValueToMinMaxProperty.OverrideDefaultValue<DataGridNumericColumn>(true);
        }

        /// <summary>
        /// Notifies the DataGrid when a property changes.
        /// </summary>
        protected override void OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
        {
            base.OnPropertyChanged(change);

            if (change.Property == FormatStringProperty
                || change.Property == NumberFormatProperty
                || change.Property == MinimumProperty
                || change.Property == MaximumProperty
                || change.Property == IncrementProperty
                || change.Property == ShowButtonSpinnerProperty
                || change.Property == ButtonSpinnerLocationProperty
                || change.Property == AllowSpinProperty
                || change.Property == ClipValueToMinMaxProperty
                || change.Property == WatermarkProperty
                || change.Property == HorizontalContentAlignmentProperty
                || change.Property == VerticalContentAlignmentProperty)
            {
                NotifyPropertyChanged(change.Property.Name);
            }
        }

        /// <summary>
        /// Causes the column cell being edited to revert to the specified value.
        /// </summary>
        protected override void CancelCellEdit(Control editingElement, object uneditedValue)
        {
            if (editingElement is NumericUpDown numericUpDown)
            {
                numericUpDown.Value = uneditedValue as decimal?;
            }
        }

        /// <summary>
        /// Creates the visual tree for read-only cells.
        /// </summary>
        protected override Control GenerateElement(DataGridCell cell, object dataItem)
        {
            if (cell is DataGridCustomDrawingCell drawingCell)
            {
                drawingCell.Theme = CellTheme ?? GetThemeValue(_drawingCellTheme);
                drawingCell.TextAlignment = GetTextAlignment();
                drawingCell.ClearValue(DataGridCustomDrawingCell.ValueProperty);

                var accessor = DataGridColumnMetadata.GetValueAccessor(this);
                if (CanUseDrawnValueAccessor(accessor, dataItem))
                {
                    drawingCell.ConfigureBuiltInRenderer(this, renderer: null);
                }
                else
                {
                    drawingCell.ConfigureBuiltInRenderer(valueProvider: null, renderer: null);
                    if (Binding != null && dataItem != DataGridCollectionView.NewItemPlaceholder)
                    {
                        drawingCell.Bind(DataGridCustomDrawingCell.ValueProperty, CreateNumericDisplayBinding(Binding));
                    }
                }

                return null;
            }

            var textBlock = new TextBlock
            {
                Name = "CellNumericTextBlock",
                VerticalAlignment = VerticalAlignment.Center
            };

            if (CellTextBlockTheme is { } theme)
            {
                textBlock.Theme = theme;
            }

            SyncDisplayProperties(textBlock);

            if (Binding != null && dataItem != DataGridCollectionView.NewItemPlaceholder)
            {
                // Create a binding with format string
                if (Binding is Binding binding)
                {
                    var displayBinding = new Binding
                    {
                        Path = binding.Path,
                        Mode = BindingMode.OneWay,
                        StringFormat = FormatString,
                        Converter = binding.Converter,
                        ConverterParameter = binding.ConverterParameter
                    };
                    textBlock.Bind(TextBlock.TextProperty, displayBinding);
                }
                else
                {
                    textBlock.Bind(TextBlock.TextProperty, Binding);
                }
            }

            return textBlock;
        }

        /// <summary>
        /// Creates the visual tree for editing cells.
        /// </summary>
        protected override Control GenerateEditingElementDirect(DataGridCell cell, object dataItem)
        {
            if (cell is DataGridCustomDrawingCell drawingCell)
            {
                drawingCell.ClearBuiltInRenderer();
                drawingCell.Theme = OwningGrid?.CellTheme ?? GetColumnControlTheme(typeof(DataGridCell));
                drawingCell.UseRetainedTemplate();
            }

            var numericUpDown = new NumericUpDown
            {
                Name = "CellNumericUpDown"
            };

            DataGridEditorFocus.ConfigureSingleTabStop(numericUpDown);

            if (CellNumericUpDownTheme is { } theme)
            {
                numericUpDown.Theme = theme;
            }

            SyncEditProperties(numericUpDown);

            return numericUpDown;
        }

        /// <summary>
        /// Called when a cell in the column enters editing mode.
        /// </summary>
        protected override object PrepareCellForEdit(Control editingElement, RoutedEventArgs editingEventArgs)
        {
            if (editingElement is NumericUpDown numericUpDown)
            {
                var uneditedValue = numericUpDown.Value;

                DataGridEditorFocus.FocusTextInput(numericUpDown, selectAll: true);

                return uneditedValue;
            }

            return null;
        }

        /// <summary>
        /// Called by the DataGrid control when this column asks for its elements to be updated.
        /// </summary>
        protected internal override void RefreshCellContent(Control element, string propertyName)
        {
            if (element == null)
            {
                throw new ArgumentNullException(nameof(element));
            }

            if (element is TextBlock textBlock)
            {
                SyncDisplayProperties(textBlock);
            }
            else if (element is DataGridCustomDrawingCell drawingCell)
            {
                drawingCell.TextAlignment = GetTextAlignment();
                drawingCell.InvalidateMeasure();
                drawingCell.InvalidateVisual();
            }
            else if (element is NumericUpDown numericUpDown)
            {
                SyncEditProperties(numericUpDown);
            }
            else
            {
                base.RefreshCellContent(element, propertyName);
            }
        }

        private void SyncDisplayProperties(TextBlock textBlock)
        {
            textBlock.TextAlignment = GetTextAlignment();

            textBlock.VerticalAlignment = IsSet(VerticalContentAlignmentProperty)
                ? VerticalContentAlignment
                : VerticalAlignment.Center;
        }

        internal override DataGridCell CreateCell() =>
            UsesDrawnDisplay ? new DataGridCustomDrawingCell() : base.CreateCell();

        internal override ControlTheme ResolveCellTheme(DataGrid grid) =>
            UsesDrawnDisplay
                ? CellTheme ?? GetThemeValue(_drawingCellTheme) ?? base.ResolveCellTheme(grid)
                : base.ResolveCellTheme(grid);

        internal override bool SupportsDrawnDisplay => true;

        object IDataGridDrawnCellValueProvider.GetDrawnCellValue(object item)
        {
            var accessor = DataGridColumnMetadata.GetValueAccessor(this);
            var value = accessor?.GetValue(item);
            if (value == null)
            {
                return null;
            }

            var formatProvider = NumberFormat ?? CultureInfo.CurrentCulture.NumberFormat;
            return value is IFormattable formattable
                ? formattable.ToString(FormatString, formatProvider)
                : Convert.ToString(value, formatProvider);
        }

        private bool CanUseDrawnValueAccessor(IDataGridColumnValueAccessor accessor, object dataItem)
        {
            return accessor != null &&
                   dataItem != null &&
                   accessor.ItemType.IsInstanceOfType(dataItem) &&
                   BindingCloneHelper.SupportsDirectDataContextRead(Binding);
        }

        private TextAlignment GetTextAlignment() => HorizontalContentAlignment switch
        {
            HorizontalAlignment.Left => TextAlignment.Left,
            HorizontalAlignment.Center => TextAlignment.Center,
            HorizontalAlignment.Right => TextAlignment.Right,
            _ => TextAlignment.Right
        };

        private BindingBase CreateNumericDisplayBinding(BindingBase binding)
        {
            if (binding is not Binding avaloniaBinding)
            {
                return binding;
            }

            return new Binding
            {
                Path = avaloniaBinding.Path,
                Mode = BindingMode.OneWay,
                StringFormat = FormatString,
                Converter = avaloniaBinding.Converter,
                ConverterCulture = avaloniaBinding.ConverterCulture,
                ConverterParameter = avaloniaBinding.ConverterParameter,
                FallbackValue = avaloniaBinding.FallbackValue,
                TargetNullValue = avaloniaBinding.TargetNullValue,
                Source = avaloniaBinding.Source,
                RelativeSource = avaloniaBinding.RelativeSource,
                ElementName = avaloniaBinding.ElementName
            };
        }

        private void SyncEditProperties(NumericUpDown numericUpDown)
        {
            if (!string.IsNullOrEmpty(FormatString))
            {
                numericUpDown.FormatString = FormatString;
            }

            if (NumberFormat != null)
            {
                numericUpDown.NumberFormat = NumberFormat;
            }

            if (IsSet(MinimumProperty))
            {
                numericUpDown.Minimum = Minimum;
            }

            if (IsSet(MaximumProperty))
            {
                numericUpDown.Maximum = Maximum;
            }

            if (IsSet(IncrementProperty))
            {
                numericUpDown.Increment = Increment;
            }

            numericUpDown.ShowButtonSpinner = ShowButtonSpinner;
            numericUpDown.ButtonSpinnerLocation = ButtonSpinnerLocation;
            numericUpDown.AllowSpin = AllowSpin;
            numericUpDown.ClipValueToMinMax = ClipValueToMinMax;

            if (!string.IsNullOrEmpty(Watermark))
            {
                numericUpDown.Watermark = Watermark;
            }

            numericUpDown.HorizontalContentAlignment = HorizontalContentAlignment;
            DataGridHelper.SyncColumnProperty(this, numericUpDown, NumericUpDown.VerticalContentAlignmentProperty, VerticalContentAlignmentProperty);
        }

        private ControlTheme GetThemeValue(Lazy<ControlTheme> themeCache)
        {
            if (themeCache.IsValueCreated)
            {
                return themeCache.Value;
            }

            // Avoid permanently caching null before the column is attached to a grid.
            return OwningGrid == null ? null : themeCache.Value;
        }
    }
}
