using System;
using System.Collections.ObjectModel;
using System.Data;
using System.Linq;
using Avalonia.Collections;
using Avalonia.Controls;
using Avalonia.Headless;
using Avalonia.Headless.XUnit;
using Avalonia.Markup.Xaml.Styling;
using Avalonia.Threading;
using Avalonia.VisualTree;
using Xunit;

namespace Avalonia.Controls.DataGridTests;

public class DataGridDataTableDisplayTests
{
    [AvaloniaFact]
    public void AutoGenerateColumns_On_Add_When_NoGeneratedColumns_Exist_Generates_Columns()
    {
        var items = new ObservableCollection<UntypedRow>();
        var root = new Window
        {
            Width = 400,
            Height = 300
        };
        root.SetThemeStyles();

        var dataGrid = new DataGrid
        {
            AutoGenerateColumns = true
        };
        bool cancelGeneration = true;
        dataGrid.AutoGeneratingColumn += (_, e) => e.Cancel = cancelGeneration;
        dataGrid.ItemsSource = items;
        root.Content = dataGrid;
        root.Show();
        PumpLayout(dataGrid);

        Assert.Empty(dataGrid.Columns);

        cancelGeneration = false;
        items.Add(new UntypedRow { Name = "First" });
        PumpLayout(dataGrid);

        Assert.Contains(dataGrid.Columns, column => Equals(column.Header, nameof(UntypedRow.Name)));

        root.Close();
    }

    [AvaloniaFact]
    public void TextInput_On_New_Row_Placeholder_Preserves_Target_Column()
    {
        DataTable table = BuildTable();
        table.Rows.Clear();
        var view = new DataGridCollectionView(table.DefaultView);
        var root = new Window
        {
            Width = 600,
            Height = 400
        };
        root.SetThemeStyles();

        var dataGrid = new DataGrid
        {
            AutoGenerateColumns = true,
            CanUserAddRows = true,
            EditTriggers = DataGridEditTriggers.TextInput,
            ItemsSource = view
        };
        root.Content = dataGrid;
        root.Show();
        PumpLayout(dataGrid);

        DataGridColumn nameColumn = dataGrid.Columns.Single(column => Equals(column.Header, "Name"));
        int nameColumnIndex = nameColumn.Index;
        Assert.True(nameColumn.IsAutoGenerated);
        int regeneratedColumnCount = 0;
        dataGrid.AutoGeneratingColumn += (_, _) => regeneratedColumnCount++;
        dataGrid.ScrollIntoView(DataGridCollectionView.NewItemPlaceholder, nameColumn);
        PumpLayout(dataGrid);
        DataGridRow placeholderRow = dataGrid.GetSelfAndVisualDescendants()
            .OfType<DataGridRow>()
            .Single(row => row.IsPlaceholder);
        DataGridCell targetCell = placeholderRow.Cells[nameColumnIndex];
        dataGrid.UpdateSelectionAndCurrency(
            nameColumnIndex,
            placeholderRow.Slot,
            DataGridSelectionAction.SelectCurrent,
            scrollIntoView: false);
        PumpLayout(dataGrid);

        int beginningEditColumnIndex = -1;
        dataGrid.BeginningEdit += (_, e) => beginningEditColumnIndex = e.Column.Index;
        Assert.True(targetCell.Focus());
        Assert.Equal(nameColumnIndex, dataGrid.CurrentColumnIndex);
        root.KeyTextInput("X");

        Assert.Equal(0, regeneratedColumnCount);
        Assert.Same(nameColumn, dataGrid.Columns[nameColumnIndex]);
        Assert.Equal(nameColumnIndex, beginningEditColumnIndex);
        Assert.Equal(nameColumnIndex, dataGrid.CurrentColumnIndex);
        Assert.Equal(nameColumnIndex, dataGrid.EditingColumnIndex);
        Assert.NotNull(dataGrid.EditingRow);
        TextBox editor = Assert.IsType<TextBox>(dataGrid.EditingRow!.Cells[nameColumnIndex].Content);
        Assert.Equal("X", editor.Text);

        root.Close();
    }

    [AvaloniaFact]
    public void DataTable_DefaultView_Does_Not_Produce_Duplicate_Visible_Rows()
    {
        var table = BuildTable();
        var view = new DataGridCollectionView(table.DefaultView);

        Assert.Equal(table.Rows.Count, view.Count);

        var root = new Window
        {
            Width = 400,
            Height = 400,
        };

        root.SetThemeStyles();

        var dataGrid = new DataGrid
        {
            AutoGenerateColumns = true,
            CanUserAddRows = false,
            ItemsSource = view,
            HeadersVisibility = DataGridHeadersVisibility.Column
        };

        root.Content = dataGrid;
        root.Show();
        dataGrid.UpdateLayout();

        var rows = dataGrid.GetSelfAndVisualDescendants()
            .OfType<DataGridRow>()
            .ToList();

        var visibleIds = rows
            .Select(r => (int)((DataRowView)r.DataContext)["Id"])
            .ToArray();

        var expectedIds = table.Rows
            .Cast<DataRow>()
            .Select(r => (int)r["Id"])
            .ToArray();

        Assert.Equal(expectedIds.Length, visibleIds.Length);
        Assert.Equal(expectedIds, visibleIds);
    }

    private static DataTable BuildTable()
    {
        var table = new DataTable("Sample");
        table.Columns.Add(new DataColumn("Id", typeof(int)));
        table.Columns.Add(new DataColumn("Name", typeof(string)));
        table.Columns.Add(new DataColumn("Balance", typeof(decimal)));
        table.Columns.Add(new DataColumn("Created", typeof(DateTimeOffset)));
        table.Columns.Add(new DataColumn("IsActive", typeof(bool)));

        for (var i = 1; i <= 8; i++)
        {
            var row = table.NewRow();
            row["Id"] = i;
            row["Name"] = $"Row {i}";
            row["Balance"] = Math.Round((i * 137.42m) % 5000 - 1200, 2);
            row["Created"] = DateTimeOffset.Now.AddHours(-i * 3);
            row["IsActive"] = i % 3 != 0;
            table.Rows.Add(row);
        }

        return table;
    }

    private static void PumpLayout(DataGrid dataGrid)
    {
        Dispatcher.UIThread.RunJobs();
        dataGrid.UpdateLayout();
        Dispatcher.UIThread.RunJobs();
    }

    private sealed class UntypedRow
    {
        public string Name { get; set; } = string.Empty;
    }

}
